name: Build OpenJDK 17 image

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build OpenJDK 17 image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the image
        working-directory: openjdk/17
        run: |
          docker buildx build \
          --tag aehrc/jre:openjdk-17 \
          --platform linux/amd64,linux/arm64 \
          --push . 
